[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.lints.clippy]
all = "warn"
nursery = "warn"
pedantic = "warn"
must_use_candidate = { level = "allow", priority = 1 }

[workspace.dependencies]
meralus-animation = { path = "./crates/animation" }
meralus-graphics = { path = "./crates/graphics" }
meralus-world = { path = "./crates/world" }
meralus-engine = { path = "./crates/engine" }
meralus-shared = { path = "./crates/shared" }
mollie-shared = { path = "./mollie/crates/shared" }
mollie-lexer = { path = "./mollie/crates/lexer" }
mollie-parser = { path = "./mollie/crates/parser" }
mollie-compiler = { path = "./mollie/crates/compiler" }
mollie-vm = { path = "./mollie/crates/vm" }
meck = { path = "./crates/meck" }
# lessor = { path = "./crates/lessor" }

glium = "0.36.0"

glam = { version = "0.30.4", features = ["serde", "bytemuck"] }
glamour = "0.18.0"

ahash = "0.8.12"
uuid = { version = "1.17.0", features = ["v4"] }

image = "0.25.6"
noise = "0.9.0"
splines = { version = "5.0.0", features = ["glam"] }

futures = { version = "0.3.31", features = ["std"] }
tokio = { version = "1.45.1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "fs",
    "sync",
    "parking_lot",
    "net",
    "io-util",
    "time",
] }
tokio-util = { version = "0.7.15", features = ["codec"] }
tokio-serde = "0.9.0"
async-compression = { version = "0.4.25", features = ["zlib", "tokio"] }
bson = "2.15.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
ariadne = "0.5.1"
derive_more = { version = "2.0.1", features = [
    "display",
    "is_variant",
    "unwrap",
] }
indexmap = "2.10.0"
peekmore = { version = "1.3.0", features = ["smallvec"] }
