[package]
name = "meck"
description = "Simple library for creating texture atlases"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { workspace = true }
glamour = { workspace = true }
image = { version = "0.25.6", default-features = false }

[lints]
workspace = true
