[package]
name = "mollie-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
mollie-shared = { workspace = true }
mollie-lexer = { workspace = true }
mollie-parser = { workspace = true }
mollie-vm = { workspace = true }
indexmap = { workspace = true }

[lints]
workspace = true
