[package]
name = "meralus-animation"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.9.0"
meralus-shared = { workspace = true }
ahash = { workspace = true }

[lints]
workspace = true
